name: Test Performance with Lighthouse

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install -g http-server
        npm install -g lighthouse
        npm install -g wait-on

    - name: Serve files
      run: |
        http-server -p 8080 &
        wait-on http://localhost:8080

    - name: Run Lighthouse
      run: |
        lighthouse http://localhost:8080 --output json --output html --output-path ./lighthouse-report.html

    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-report
        path: ./lighthouse-report.html
